global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: "10s" # scrape_timeout is set to the global default (10s).

rule_files:

scrape_configs:

  - job_name: 'prometheus'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - prometheus:9090

  - job_name: ticket-sales-metrics
    metrics_path: /metrics
    static_configs:
      - targets:
        - app:8000
