"""create event table

Revision ID: 5b1bc38589cf
Revises: e0db7453646d
Create Date: 2023-08-31 15:59:11.518462

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5b1bc38589cf'
down_revision: Union[str, None] = 'e0db7453646d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_spot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_reserved', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['event_section.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'customer', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_table('event_spot')
    # ### end Alembic commands ###
